[programs.localnet]
anchor_escrow = "AGtT2X117M7Lx1PeXQrknorvwApEdBSUsAiYA2R2QESd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://rpc-mainnet-fork.dappio.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
