[programs.localnet]
anchor_escrow = "4CkSf34hTH2rGmgFDCm5WCFE8sHpfdBzrBChEScJBxoM"

[provider]
cluster = "https://rpc-mainnet-fork.dappio.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
